apiVersion: tekton.dev/v1beta1
kind: TriggerTemplate
metadata:
  name: template
spec:
  params:
    - name: cluster
      description: the cluster
  resourcetemplates:
    - apiVersion: v1
      kind: PersistentVolumeClaim
      metadata:
        name: pipelinerun-$(uid)-pvc
      spec:
        resources:
          requests:
            storage:  5Gi
        volumeMode: Filesystem
        accessModes:
          - ReadWriteOnce
    - apiVersion: tekton.dev/v1beta1
      kind: PipelineRun
      metadata:
        name: pipelinerun-$(uid)
      spec:
        pipelineRef:
            name: deploy-pipeline
        workspaces:
          - name: pipeline-pvc
            persistentVolumeClaim:
              claimName: pipelinerun-$(uid)-pvc
        params:
        - name: cluster
          value: $(params.cluster)
---
apiVersion: tekton.dev/v1beta1
kind: TriggerBinding
metadata:
  name: binding
spec:
  params:
    - name: cluster
      value: "bog-cluster"
---
apiVersion: tekton.dev/v1beta1
kind: EventListener
metadata:
  name: deploy-listener
spec:
  triggers:
    - name: bog-trig
      bindings:
        - ref: binding
      template:
        ref: template
