apiVersion: tekton.dev/v1beta1
kind: Pipeline
metadata:
  name: deploy-pipeline
spec:
  params:
    - name: cluster
      description: the cluster to deploy to
  workspaces:
  - name: pipeline-pvc
  tasks:  
    - name: deploy-with-kubectl
      taskRef:
        name: deploy-with-kubectl
      params:
        - name: cluster
          value: $(params.cluster)
      workspaces:
      - name: task-pvc
        workspace: pipeline-pvc  

